name: SimpleBlockCommands
version: ${project.version}
main: net.mctechnic.simpleblockcommands.SimpleBlockCommands
api-version: 1.18
author: TechnicJelle
description: ${project.description}
website: ${project.url}
commands:
  sbc:
    usage: Use /sbc reload
    description: Reloads the blockCommands.conf file with the block locations and commands
    permission: simpleblockcommands.commands.reload
permissions:
  simpleblockcommands.*:
    children:
      simpleblockcommands.commands.*: true
    default: op
    description: All permissions for the Simple Block Commands plugin
  simpleblockcommands.commands.*:
    children:
      simpleblockcommands.commands.reload: true
    default: op
    description: Permission for all commands
  simpleblockcommands.commands.reload:
    default: op
    description: Permission for the /sbc reload command

